### ISSUE TITLE
Before content will not parsed 

### ISSUE THREAD

**Issue by flemming-pr** [visuellverstehen/statamic-classify#25]
The following will result in this in the frontend

Config.php
`'li' => 'before:content-["- "]',`

Frontend
`class="before:content-[" -="" "]"=""`

**Comment by lakkes-ra** [comment]
Hi @flemming-pr Sorry that i took so long to answer.

I can't reproduce the error you submitted, but I can reproduce the browser not rendering `'before:content-["- "]'` correct. That's because the use of the whitespace character. That's due to tailwindcss. It also happens outside of the classify config. 

What you can do is:
`'li' => 'before:content-["-"]',` 
and then use css styling to apply the gap.

In addition you can use escaped single quotes in the config to prevent any single double quote confusion in the rendered HTML. 

`'li' => 'before:content-[\'-\']',`
